version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Installing yarn
            - npm i -g yarn
    pre_build:
        commands:
            - echo Installing NPM dependencies...
            - yarn
            - yarn run dev
    build:
        commands:
            - echo Build started on `date`
    post_build:
        commands:
            - echo Build completed on `date`