// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// TWO FACTOR
export const SAVE_TWOFACTOR_TOKEN = 'SAVE_TWOFACTOR_TOKEN'
export const REMOVE_TWOFACTOR_TOKEN = 'REMOVE_TWOFACTOR_TOKEN'

// order
export const UPDATE_ORDER = 'UPDATE_ORDER'

// settings
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS'
export const FETCH_SETTINGS_FAILURE = 'FETCH_SETTINGS_FAILURE'
